# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion -Wshadow \
-Wformat=2 -Wnull-dereference -Wdouble-promotion -Wcast-align \
-Wstrict-prototypes -Werror -g -O2 -std=gnu99

# Source and object files
SRC = main.c libs/tiltyard/src/tiltyard_API.c libs/tiltyard/src/tiltyard_Error.c src/error/handle_error.c src/fileio/input/file_i.c
OBJ = $(SRC:.c=.o)
TARGET = fas

# Build target
$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

# Compile .c to .o (automatic dependency generation)
%.o: %.c
	$(CC) $(CFLAGS) -MMD -c $< -o $@

# Include dependency files generated by -MMD
-include $(OBJ:.o=.d)

# Clean object files, dependency files, and binary
clean:
	rm -f $(OBJ) $(OBJ:.o=.d)

